Update rcmdcheck.yaml

diff --git a/.github/workflows/rcmdcheck.yaml b/.github/workflows/rcmdcheck.yaml
--- a/.github/workflows/rcmdcheck.yaml
+++ b/.github/workflows/rcmdcheck.yaml
@@ -1,139 +1,139 @@
-# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
-# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
-on:
-  schedule:
-  - cron: '0 0 * * *'
-  push:
-    branches:
-      - main
-      - master
-  pull_request:
-    branches:
-      - main
-      - master
-
-name: R-CMD-check
-
-jobs:
-  R-CMD-check:
-    runs-on: ${{ matrix.config.os }}
-
-    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
-
-    strategy:
-      fail-fast: false
-      matrix:
-        config:
-          - {os: windows-latest, r: 'release'}
-          - {os: ubuntu-22.04, r: 'release', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"}
-          - {os: ubuntu-24.04, r: 'devel', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"}
-          #- {os: ubuntu-20.04, r: 'oldrel', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"}
-
-    env:
-      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
-      RSPM: ${{ matrix.config.rspm }}
-      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
-      KMP_DUPLICATE_LIB_OK: TRUE
-    steps:
-      - uses: actions/checkout@v4
-
-      - uses: r-lib/actions/setup-r@v2
-        with:
-          r-version: ${{ matrix.config.r }}
-
-      - uses: r-lib/actions/setup-pandoc@v2
-      
-      # - name: TinyTex for non Windows
-      #   if: runner.os != 'Windows'
-      #   uses: r-lib/actions/setup-tinytex@v2
-      #   env:
-      #     TINYTEX_INSTALLER: TinyTeX
-      #     #TINYTEX_VERSION: '2023.03'
-      # 
-      # - name: TinyTex for Windows
-      #   if: runner.os == 'Windows'
-      #   uses: r-lib/actions/setup-tinytex@v2
-      #   env:
-      #     TINYTEX_INSTALLER: TinyTeX
-      #     TINYTEX_VERSION: '2023.03'
-      #     
-      # - name: TinyTex2 for Windows
-      #   if: runner.os == 'Windows'
-      #   uses: teatimeguest/setup-texlive-action@v2
-      # 
-      # - name: Install makeindex
-      #   run: |
-      #     tlmgr install makeindex
-
-      - name: Query dependencies
-        run: |
-          setwd("sjSDM")
-          install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")
-          saveRDS(pak::pkg_deps("local::.", dependencies = TRUE), "../.github/r-depends.rds")
-        shell: Rscript {0}
-
-      - name: Cache R packages
-        if: runner.os != 'Windows'
-        uses: actions/cache@v4
-        with:
-          path: ${{ env.R_LIBS_USER }}
-          key: ${{ matrix.config.os }}-${{ steps.install-r.outputs.installed-r-version }}-1-${{ hashFiles('.github/r-depends.rds') }}
-          restore-keys: ${{ matrix.config.os }}-${{ steps.install-r.outputs.installed-r-version }}-1-
-
-      - name: Install curl for r-devel version
-        if: runner.os == 'Linux'
-        run: |
-          sudo apt-get install -y curl
-          sudo apt-get install -y texlive texlive-fonts-extra
-
-      - name: Install system dependencies
-        if: runner.os == 'Linux'
-        run: |
-          setwd("sjSDM")
-          pak::local_system_requirements(execute = TRUE)
-          pak::pkg_system_requirements("rcmdcheck", execute = TRUE)
-        shell: Rscript {0}
-
-      - name: Install dependencies
-        run: |
-          setwd("sjSDM")
-          pak::local_install_dev_deps(upgrade = TRUE)
-          pak::pkg_install("rcmdcheck")
-        shell: Rscript {0}
-        
-      - name: Install Pkg
-        run: |
-          cd sjSDM
-          Rscript -e "pak::local_install()"
-          Rscript -e "pak::pkg_install('rstudio/reticulate')"
-          Rscript -e "sjSDM::install_sjSDM(version='cpu')"
-          
-      - name: Check I
-        env:
-          _R_CHECK_CRAN_INCOMING_REMOTE_: false
-          CI: true
-        run: |
-          options(crayon.enabled = TRUE)
-          rcmdcheck::rcmdcheck("sjSDM", args = c("--no-multiarch", "--no-manual"), error_on = "error", check_dir = "check")
-        shell: Rscript {0}
-        
-      - name: testthat output
-        if: always()
-        run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
-        shell: bash
-        
-      - name: Check II
-        env:
-          _R_CHECK_CRAN_INCOMING_REMOTE_: false
-          CI: true
-        run: |
-          options(crayon.enabled = TRUE)
-          rcmdcheck::rcmdcheck("sjSDM", args = c("--no-manual", "--as-cran"), error_on = "note", check_dir = "check")
-        shell: Rscript {0}
-        
-      - name: Upload check results
-        if: failure()
-        uses: actions/upload-artifact@main
-        with:
-          name: ${{ matrix.config.os }}-r${{ matrix.config.r }}-results
-          path: check
+# # For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
+# # https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
+# on:
+#   schedule:
+#   - cron: '0 0 * * *'
+#   push:
+#     branches:
+#       - main
+#       - master
+#   pull_request:
+#     branches:
+#       - main
+#       - master
+# 
+# name: R-CMD-check
+# 
+# jobs:
+#   R-CMD-check:
+#     runs-on: ${{ matrix.config.os }}
+# 
+#     name: ${{ matrix.config.os }} (${{ matrix.config.r }})
+# 
+#     strategy:
+#       fail-fast: false
+#       matrix:
+#         config:
+#           - {os: windows-latest, r: 'release'}
+#           - {os: ubuntu-22.04, r: 'release', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"}
+#           - {os: ubuntu-24.04, r: 'devel', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"}
+#           #- {os: ubuntu-20.04, r: 'oldrel', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"}
+# 
+#     env:
+#       R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
+#       RSPM: ${{ matrix.config.rspm }}
+#       GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
+#       KMP_DUPLICATE_LIB_OK: TRUE
+#     steps:
+#       - uses: actions/checkout@v4
+# 
+#       - uses: r-lib/actions/setup-r@v2
+#         with:
+#           r-version: ${{ matrix.config.r }}
+# 
+#       - uses: r-lib/actions/setup-pandoc@v2
+#       
+#       # - name: TinyTex for non Windows
+#       #   if: runner.os != 'Windows'
+#       #   uses: r-lib/actions/setup-tinytex@v2
+#       #   env:
+#       #     TINYTEX_INSTALLER: TinyTeX
+#       #     #TINYTEX_VERSION: '2023.03'
+#       # 
+#       # - name: TinyTex for Windows
+#       #   if: runner.os == 'Windows'
+#       #   uses: r-lib/actions/setup-tinytex@v2
+#       #   env:
+#       #     TINYTEX_INSTALLER: TinyTeX
+#       #     TINYTEX_VERSION: '2023.03'
+#       #     
+#       # - name: TinyTex2 for Windows
+#       #   if: runner.os == 'Windows'
+#       #   uses: teatimeguest/setup-texlive-action@v2
+#       # 
+#       # - name: Install makeindex
+#       #   run: |
+#       #     tlmgr install makeindex
+# 
+#       - name: Query dependencies
+#         run: |
+#           setwd("sjSDM")
+#           install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")
+#           saveRDS(pak::pkg_deps("local::.", dependencies = TRUE), "../.github/r-depends.rds")
+#         shell: Rscript {0}
+# 
+#       - name: Cache R packages
+#         if: runner.os != 'Windows'
+#         uses: actions/cache@v4
+#         with:
+#           path: ${{ env.R_LIBS_USER }}
+#           key: ${{ matrix.config.os }}-${{ steps.install-r.outputs.installed-r-version }}-1-${{ hashFiles('.github/r-depends.rds') }}
+#           restore-keys: ${{ matrix.config.os }}-${{ steps.install-r.outputs.installed-r-version }}-1-
+# 
+#       - name: Install curl for r-devel version
+#         if: runner.os == 'Linux'
+#         run: |
+#           sudo apt-get install -y curl
+#           sudo apt-get install -y texlive texlive-fonts-extra
+# 
+#       - name: Install system dependencies
+#         if: runner.os == 'Linux'
+#         run: |
+#           setwd("sjSDM")
+#           pak::local_system_requirements(execute = TRUE)
+#           pak::pkg_system_requirements("rcmdcheck", execute = TRUE)
+#         shell: Rscript {0}
+# 
+#       - name: Install dependencies
+#         run: |
+#           setwd("sjSDM")
+#           pak::local_install_dev_deps(upgrade = TRUE)
+#           pak::pkg_install("rcmdcheck")
+#         shell: Rscript {0}
+#         
+#       - name: Install Pkg
+#         run: |
+#           cd sjSDM
+#           Rscript -e "pak::local_install()"
+#           Rscript -e "pak::pkg_install('rstudio/reticulate')"
+#           Rscript -e "sjSDM::install_sjSDM(version='cpu')"
+#           
+#       - name: Check I
+#         env:
+#           _R_CHECK_CRAN_INCOMING_REMOTE_: false
+#           CI: true
+#         run: |
+#           options(crayon.enabled = TRUE)
+#           rcmdcheck::rcmdcheck("sjSDM", args = c("--no-multiarch", "--no-manual"), error_on = "error", check_dir = "check")
+#         shell: Rscript {0}
+#         
+#       - name: testthat output
+#         if: always()
+#         run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
+#         shell: bash
+#         
+#       - name: Check II
+#         env:
+#           _R_CHECK_CRAN_INCOMING_REMOTE_: false
+#           CI: true
+#         run: |
+#           options(crayon.enabled = TRUE)
+#           rcmdcheck::rcmdcheck("sjSDM", args = c("--no-manual", "--as-cran"), error_on = "note", check_dir = "check")
+#         shell: Rscript {0}
+#         
+#       - name: Upload check results
+#         if: failure()
+#         uses: actions/upload-artifact@main
+#         with:
+#           name: ${{ matrix.config.os }}-r${{ matrix.config.r }}-results
+#           path: check
